# Generated by Django 4.2.5 on 2023-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_lang',
            field=models.CharField(default='en', max_length=3),
        ),
    ]
