# Generated by Django 4.2.5 on 2023-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(max_length=200),
        ),
    ]
