# Generated by Django 4.2.5 on 2023-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='langs',
            field=models.ManyToManyField(default=1, related_name='book_langs', to='book.lang'),
        ),
    ]
