# Generated by Django 4.2.5 on 2023-09-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_lang_book_langs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='main_lang',
        ),
    ]
