# Generated by Django 4.2.5 on 2023-09-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'ordering': ('datetime_created',)},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='book.category'),
        ),
    ]
