# Generated by Django 4.2.5 on 2023-09-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_options_book_isbn_book_page_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfile',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_files', to='book.book'),
        ),
    ]
