# Generated by Django 4.2.5 on 2023-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('accounts', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='book.book'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
