# Generated by Django 4.2.5 on 2023-09-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
