# Generated by Django 4.2.5 on 2023-09-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coupon_premiumplan_premiumorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='PremiumOrder',
        ),
        migrations.DeleteModel(
            name='PremiumPlan',
        ),
    ]
