services:
  django:
    image: beytoote:1.1.2
    container_name: beytoote
    build: .
    env_file:
      - .env
    expose:
      - "8000"
    restart: always
    networks:
      - beytoote_net
    ports:
      - "8000:8000"

networks:
  beytoote_net: