# Generated by Django 4.2.5 on 2023-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumorder',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
