# Generated by Django 4.2.5 on 2023-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_premiumorder_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
