# Generated by Django 4.2.5 on 2023-09-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_premiumplan_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumplan',
            options={'ordering': ('-price',)},
        ),
    ]
